### ISSUE TITLE
'Observable<boolean> | boolean'.  Type 'Observable<{}>' is not assignable to type 'boolean'.

### ISSUE THREAD

**Issue by samirthebti** [choopage/angular2-rc4-auth-routing#1] opened 2016-07-07 22:14 UTC
I started testing your project and i get the error : 

```
Error:(81, 12) TS2322: Type 'Observable<{}>' is not assignable to type 'Observable<boolean> | boolean'.
 Type 'Observable<{}>' is not assignable to type 'boolean'.
```

**Comment by jek-bao-choo** [comment] 2016-07-08 00:19
Did you 'NPM install' ? also typings install? I am using my mobile to view this. Can't share much until i access my workstation.

**Comment by jek-bao-choo** [comment] 2016-07-08 02:15
@samirthebti I need your help. Could you share with me:
1. how/what code you did execute to reproduce the problem??
2. what is in your environment and package.json e.g. `npm -g outdated`

Personally I didn't experience this when `ng build && ng serve`. So my best bet is to reproduce the same problem and try my best to resolve it.

This project that I committed works well for me.

**Closed as completed** 2016-07-15 12:56 UTC

**Comment by jek-bao-choo** [comment] 2016-07-15 12:57
hi @samirthebti this issue is now resolved. It's due to Typings problem
